//package ru.digdes.steammarketparser.model.utils;
//
//import org.hibernate.Session;
//import org.hibernate.SessionFactory;
//import ru.digdes.steammarketparser.model.entity.Item;
//import ru.digdes.steammarketparser.model.entity.ItemTracking;
//import ru.digdes.steammarketparser.model.entity.Price;
//import ru.digdes.steammarketparser.model.entity.User;
//
//import java.util.ArrayList;
//import java.util.List;
//
///**
// * Tests data getting generated by InitialDataGenerator
// *
// * @see InitialDataGenerator
// */
//public class HibernateDataGetter {
//    private static SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
//
//    public static void testDatabaseAndViewResults() {
//        List<User> users = new ArrayList<>();
//        List<Item> items = new ArrayList<>();
//        List<Price> prices = new ArrayList<>();
//        List<ItemTracking> itemTrackings = new ArrayList<>();
//
//        try (Session session = sessionFactory.openSession()) {
//            session.beginTransaction();
//
//            for (long userID = 1; userID <= 4; userID++) {
//                users.add(session.get(User.class, userID));
//            }
//
//            for (long itemID = 1; itemID <= 3; itemID++) {
//                items.add(session.get(Item.class, itemID));
//            }
//
//            for (long priceID = 1; priceID <= 6; priceID++) {
//                prices.add(session.get(Price.class, priceID));
//            }
//
//            for (long itemTrackingID = 1; itemTrackingID <= 5; itemTrackingID++) {
//                itemTrackings.add(session.get(ItemTracking.class, itemTrackingID));
//            }
//
//            printList(users);
//            printList(items);
//            printList(prices);
//            printList(itemTrackings);
//        }
//    }
//
//    private static void printList(List<?> list) {
//        System.out.println("------------------------------------");
//        System.out.println("List of " + list.get(0).getClass().getSimpleName() + "s:");
//        for (Object obj : list) {
//            System.out.println(obj.toString());
//        }
//    }
//}
